#ifndef JSON_CONFIG_H
#define JSON_CONFIG_H

#define JSON_C_HAVE_INTTYPES_H 1
#define JSON_C_HAVE_STDINT_H 1
#define JSON_C_HAVE_SYS_TYPES_H 1
#define JSON_C_HAVE_SYS_STAT_H 1
#define JSON_C_HAVE_STDLIB_H 1
#define JSON_C_HAVE_STRING_H 1
#define JSON_C_HAVE_STRINGS_H 1
#define JSON_C_HAVE_UNISTD_H 1
#define JSON_C_HAVE_LOCALE_H 1
#define JSON_C_HAVE_MEMORY_H 1

#define JSON_C_HAVE_STRCASECMP 1
#define JSON_C_HAVE_STRNCASECMP 1
#define JSON_C_HAVE_STRDUP 1
#define JSON_C_HAVE_USELOCALE 1
#define JSON_C_HAVE_DECL_INFINITY 1
#define JSON_C_HAVE_DECL_NAN 1

#endif
